#! /bin/sh

bspc config top_padding         25

bspc config border_width        1
bspc config window_gap          20

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

#bspc config focus_follows_pointer true

(( $(bspc query -M | wc -l) == 1 )) &&\
  bspc monitor -d 1 2 3 4 5 ||\
  (bspc monitor DVI-I-2 -n 0 -d 1 2 3 4 5
  bspc monitor DVI-I-1 -n 1 -d 6 7 8 9 10)

bspc config --desktop 1 window_gap 0

bspc rule -a Firefox    desktop=^1  follow=off border=off
bspc rule -a Keepassx   floating=on
bspc rule -a Steam      desktop=^3  follow=off
bspc rule -a Kodi       desktop=^2  follow=off
bspc rule -a Obshutdown floating=on

tint2&
sxhkd&
~/.scripts/autostart.sh&
