#! /bin/sh

bspc config top_padding        20

bspc config border_width        1
bspc config window_gap         10

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true

bspc monitor -d 1 2 3 4 5
bspc config --desktop 1 window_gap 0

bspc rule -a Firefox desktop=^1 follow=off border=off
bspc rule -a Keepassx floating=on
bspc rule -a Steam desktop=^3 follow=off
bspc rule -a Kodi desktop=^2 follow=off
bspc rule -a Obshutdown floating=on

tint2&
sxhkd&
~/.scripts/autostart.sh&
